### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by antagomir**
Minor updates.

The `devtools::document()` does not go through. But it is not strictly required for github version since it can be generated automatically. Hence I am opening this PR, if it is OK otherwise it could be merged and then we can troubleshoot document() separately.

### CODE REVIEW

**Comment by TuomasBorman** [comment]
* checking DESCRIPTION meta-information ... OK
Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
  PCRE pattern compilation error
	'quantifier does not follow a repeatable item'
	at '*~'
Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
  invalid regular expression '*~'
Execution halted
Error: Failed to install 'MGnifyR' from local:
  ! System command 'R' failed
Execution halted
Error: Process completed with exit code 1.

**Comment by antagomir** [comment]
That error is now resolved.

**Comment by antagomir** [comment]
Hmm - - I have no errors with this PR in local builds.

However I had to comment out the last test in `test-getResult.R` to get through GHA checks.

In addition, there seem to be now warnings about undocumented objects. Many of these are documented as far as I could see, not sure how this issue arises and whether it is related to this particular PR.

@TuomasBorman what's your take on this, could we merge these current updates and then troubleshoot those things separately? Might be easiest to isolate the different issues. Alternatively, we can continue to keep this open and try fix somehow.

**Comment by TuomasBorman** [comment]
My local checks are also ok. I check if I manage to find the answer --> it would be better to solve this issue now when this should be quite simple problem (not much is changed)

**Comment by antagomir** [comment]
Ah of course.

**Pull request merged**
